// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/Vladislav747/golang-project-order-system/internal/model"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *MockService) CreateOrder(ctx context.Context, order model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *MockService_Expecter) CreateOrder(ctx interface{}, order interface{}) *MockService_CreateOrder_Call {
	return &MockService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *MockService_CreateOrder_Call) Run(run func(ctx context.Context, order model.Order)) *MockService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *MockService_CreateOrder_Call) Return(_a0 error) *MockService_CreateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_CreateOrder_Call) RunAndReturn(run func(context.Context, model.Order) error) *MockService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrderKafka provides a mock function with given fields: ctx, order
func (_m *MockService) CreateOrderKafka(ctx context.Context, order model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrderKafka")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_CreateOrderKafka_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrderKafka'
type MockService_CreateOrderKafka_Call struct {
	*mock.Call
}

// CreateOrderKafka is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *MockService_Expecter) CreateOrderKafka(ctx interface{}, order interface{}) *MockService_CreateOrderKafka_Call {
	return &MockService_CreateOrderKafka_Call{Call: _e.mock.On("CreateOrderKafka", ctx, order)}
}

func (_c *MockService_CreateOrderKafka_Call) Run(run func(ctx context.Context, order model.Order)) *MockService_CreateOrderKafka_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *MockService_CreateOrderKafka_Call) Return(_a0 error) *MockService_CreateOrderKafka_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_CreateOrderKafka_Call) RunAndReturn(run func(context.Context, model.Order) error) *MockService_CreateOrderKafka_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrder provides a mock function with given fields: ctx, id
func (_m *MockService) DeleteOrder(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrder'
type MockService_DeleteOrder_Call struct {
	*mock.Call
}

// DeleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) DeleteOrder(ctx interface{}, id interface{}) *MockService_DeleteOrder_Call {
	return &MockService_DeleteOrder_Call{Call: _e.mock.On("DeleteOrder", ctx, id)}
}

func (_c *MockService_DeleteOrder_Call) Run(run func(ctx context.Context, id string)) *MockService_DeleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeleteOrder_Call) Return(_a0 error) *MockService_DeleteOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteOrder_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrderKafka provides a mock function with given fields: ctx, id
func (_m *MockService) DeleteOrderKafka(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrderKafka")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteOrderKafka_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrderKafka'
type MockService_DeleteOrderKafka_Call struct {
	*mock.Call
}

// DeleteOrderKafka is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) DeleteOrderKafka(ctx interface{}, id interface{}) *MockService_DeleteOrderKafka_Call {
	return &MockService_DeleteOrderKafka_Call{Call: _e.mock.On("DeleteOrderKafka", ctx, id)}
}

func (_c *MockService_DeleteOrderKafka_Call) Run(run func(ctx context.Context, id string)) *MockService_DeleteOrderKafka_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeleteOrderKafka_Call) Return(_a0 error) *MockService_DeleteOrderKafka_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteOrderKafka_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeleteOrderKafka_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSoftOrder provides a mock function with given fields: ctx, id
func (_m *MockService) DeleteSoftOrder(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSoftOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteSoftOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSoftOrder'
type MockService_DeleteSoftOrder_Call struct {
	*mock.Call
}

// DeleteSoftOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) DeleteSoftOrder(ctx interface{}, id interface{}) *MockService_DeleteSoftOrder_Call {
	return &MockService_DeleteSoftOrder_Call{Call: _e.mock.On("DeleteSoftOrder", ctx, id)}
}

func (_c *MockService_DeleteSoftOrder_Call) Run(run func(ctx context.Context, id string)) *MockService_DeleteSoftOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeleteSoftOrder_Call) Return(_a0 error) *MockService_DeleteSoftOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteSoftOrder_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeleteSoftOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *MockService) GetOrder(ctx context.Context, id string) (model.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) GetOrder(ctx interface{}, id interface{}) *MockService_GetOrder_Call {
	return &MockService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *MockService_GetOrder_Call) Run(run func(ctx context.Context, id string)) *MockService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetOrder_Call) Return(_a0 model.Order, _a1 error) *MockService_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetOrder_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *MockService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function with given fields: ctx
func (_m *MockService) GetOrders(ctx context.Context) ([]model.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockService_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetOrders(ctx interface{}) *MockService_GetOrders_Call {
	return &MockService_GetOrders_Call{Call: _e.mock.On("GetOrders", ctx)}
}

func (_c *MockService_GetOrders_Call) Run(run func(ctx context.Context)) *MockService_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetOrders_Call) Return(_a0 []model.Order, _a1 error) *MockService_GetOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetOrders_Call) RunAndReturn(run func(context.Context) ([]model.Order, error)) *MockService_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, order
func (_m *MockService) UpdateOrder(ctx context.Context, order model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type MockService_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *MockService_Expecter) UpdateOrder(ctx interface{}, order interface{}) *MockService_UpdateOrder_Call {
	return &MockService_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, order)}
}

func (_c *MockService_UpdateOrder_Call) Run(run func(ctx context.Context, order model.Order)) *MockService_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *MockService_UpdateOrder_Call) Return(_a0 error) *MockService_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UpdateOrder_Call) RunAndReturn(run func(context.Context, model.Order) error) *MockService_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderKafka provides a mock function with given fields: ctx, order
func (_m *MockService) UpdateOrderKafka(ctx context.Context, order model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderKafka")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UpdateOrderKafka_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderKafka'
type MockService_UpdateOrderKafka_Call struct {
	*mock.Call
}

// UpdateOrderKafka is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *MockService_Expecter) UpdateOrderKafka(ctx interface{}, order interface{}) *MockService_UpdateOrderKafka_Call {
	return &MockService_UpdateOrderKafka_Call{Call: _e.mock.On("UpdateOrderKafka", ctx, order)}
}

func (_c *MockService_UpdateOrderKafka_Call) Run(run func(ctx context.Context, order model.Order)) *MockService_UpdateOrderKafka_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *MockService_UpdateOrderKafka_Call) Return(_a0 error) *MockService_UpdateOrderKafka_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UpdateOrderKafka_Call) RunAndReturn(run func(context.Context, model.Order) error) *MockService_UpdateOrderKafka_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
