// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	order_event_v1 "github.com/Vladislav747/golang-project-order-system/internal/pkg/api/order_event/v1"
)

// MockOrderEventServiceClient is an autogenerated mock type for the OrderEventServiceClient type
type MockOrderEventServiceClient struct {
	mock.Mock
}

type MockOrderEventServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderEventServiceClient) EXPECT() *MockOrderEventServiceClient_Expecter {
	return &MockOrderEventServiceClient_Expecter{mock: &_m.Mock}
}

// GetOrderEvents provides a mock function with given fields: ctx, in, opts
func (_m *MockOrderEventServiceClient) GetOrderEvents(ctx context.Context, in *order_event_v1.GetOrderEventsRequest, opts ...grpc.CallOption) (*order_event_v1.GetOrderEventsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderEvents")
	}

	var r0 *order_event_v1.GetOrderEventsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_event_v1.GetOrderEventsRequest, ...grpc.CallOption) (*order_event_v1.GetOrderEventsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_event_v1.GetOrderEventsRequest, ...grpc.CallOption) *order_event_v1.GetOrderEventsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_event_v1.GetOrderEventsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_event_v1.GetOrderEventsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderEventServiceClient_GetOrderEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderEvents'
type MockOrderEventServiceClient_GetOrderEvents_Call struct {
	*mock.Call
}

// GetOrderEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - in *order_event_v1.GetOrderEventsRequest
//   - opts ...grpc.CallOption
func (_e *MockOrderEventServiceClient_Expecter) GetOrderEvents(ctx interface{}, in interface{}, opts ...interface{}) *MockOrderEventServiceClient_GetOrderEvents_Call {
	return &MockOrderEventServiceClient_GetOrderEvents_Call{Call: _e.mock.On("GetOrderEvents",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockOrderEventServiceClient_GetOrderEvents_Call) Run(run func(ctx context.Context, in *order_event_v1.GetOrderEventsRequest, opts ...grpc.CallOption)) *MockOrderEventServiceClient_GetOrderEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*order_event_v1.GetOrderEventsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockOrderEventServiceClient_GetOrderEvents_Call) Return(_a0 *order_event_v1.GetOrderEventsResponse, _a1 error) *MockOrderEventServiceClient_GetOrderEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderEventServiceClient_GetOrderEvents_Call) RunAndReturn(run func(context.Context, *order_event_v1.GetOrderEventsRequest, ...grpc.CallOption) (*order_event_v1.GetOrderEventsResponse, error)) *MockOrderEventServiceClient_GetOrderEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderEventServiceClient creates a new instance of MockOrderEventServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderEventServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderEventServiceClient {
	mock := &MockOrderEventServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
