// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockUnsafeOrderEventServiceServer is an autogenerated mock type for the UnsafeOrderEventServiceServer type
type MockUnsafeOrderEventServiceServer struct {
	mock.Mock
}

type MockUnsafeOrderEventServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeOrderEventServiceServer) EXPECT() *MockUnsafeOrderEventServiceServer_Expecter {
	return &MockUnsafeOrderEventServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedOrderEventServiceServer provides a mock function with no fields
func (_m *MockUnsafeOrderEventServiceServer) mustEmbedUnimplementedOrderEventServiceServer() {
	_m.Called()
}

// MockUnsafeOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedOrderEventServiceServer'
type MockUnsafeOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedOrderEventServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeOrderEventServiceServer_Expecter) mustEmbedUnimplementedOrderEventServiceServer() *MockUnsafeOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call {
	return &MockUnsafeOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedOrderEventServiceServer")}
}

func (_c *MockUnsafeOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call) Run(run func()) *MockUnsafeOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call) Return() *MockUnsafeOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call) RunAndReturn(run func()) *MockUnsafeOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockUnsafeOrderEventServiceServer creates a new instance of MockUnsafeOrderEventServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeOrderEventServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeOrderEventServiceServer {
	mock := &MockUnsafeOrderEventServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
