// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	order_event_v1 "github.com/Vladislav747/golang-project-order-system/internal/pkg/api/order_event/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderEventServiceServer is an autogenerated mock type for the OrderEventServiceServer type
type MockOrderEventServiceServer struct {
	mock.Mock
}

type MockOrderEventServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderEventServiceServer) EXPECT() *MockOrderEventServiceServer_Expecter {
	return &MockOrderEventServiceServer_Expecter{mock: &_m.Mock}
}

// GetOrderEvents provides a mock function with given fields: _a0, _a1
func (_m *MockOrderEventServiceServer) GetOrderEvents(_a0 context.Context, _a1 *order_event_v1.GetOrderEventsRequest) (*order_event_v1.GetOrderEventsResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderEvents")
	}

	var r0 *order_event_v1.GetOrderEventsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_event_v1.GetOrderEventsRequest) (*order_event_v1.GetOrderEventsResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_event_v1.GetOrderEventsRequest) *order_event_v1.GetOrderEventsResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_event_v1.GetOrderEventsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_event_v1.GetOrderEventsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderEventServiceServer_GetOrderEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderEvents'
type MockOrderEventServiceServer_GetOrderEvents_Call struct {
	*mock.Call
}

// GetOrderEvents is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *order_event_v1.GetOrderEventsRequest
func (_e *MockOrderEventServiceServer_Expecter) GetOrderEvents(_a0 interface{}, _a1 interface{}) *MockOrderEventServiceServer_GetOrderEvents_Call {
	return &MockOrderEventServiceServer_GetOrderEvents_Call{Call: _e.mock.On("GetOrderEvents", _a0, _a1)}
}

func (_c *MockOrderEventServiceServer_GetOrderEvents_Call) Run(run func(_a0 context.Context, _a1 *order_event_v1.GetOrderEventsRequest)) *MockOrderEventServiceServer_GetOrderEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*order_event_v1.GetOrderEventsRequest))
	})
	return _c
}

func (_c *MockOrderEventServiceServer_GetOrderEvents_Call) Return(_a0 *order_event_v1.GetOrderEventsResponse, _a1 error) *MockOrderEventServiceServer_GetOrderEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderEventServiceServer_GetOrderEvents_Call) RunAndReturn(run func(context.Context, *order_event_v1.GetOrderEventsRequest) (*order_event_v1.GetOrderEventsResponse, error)) *MockOrderEventServiceServer_GetOrderEvents_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedOrderEventServiceServer provides a mock function with no fields
func (_m *MockOrderEventServiceServer) mustEmbedUnimplementedOrderEventServiceServer() {
	_m.Called()
}

// MockOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedOrderEventServiceServer'
type MockOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedOrderEventServiceServer is a helper method to define mock.On call
func (_e *MockOrderEventServiceServer_Expecter) mustEmbedUnimplementedOrderEventServiceServer() *MockOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call {
	return &MockOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedOrderEventServiceServer")}
}

func (_c *MockOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call) Run(run func()) *MockOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call) Return() *MockOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call) RunAndReturn(run func()) *MockOrderEventServiceServer_mustEmbedUnimplementedOrderEventServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockOrderEventServiceServer creates a new instance of MockOrderEventServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderEventServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderEventServiceServer {
	mock := &MockOrderEventServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
