version: "2"

run:
  go: "1.25"
  timeout: 5m

linters:
  default: none

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/Vladislav747/golang-project-order-system)
