run:
  go: "1.22"

linters:
  enable:
    - gofumpt
    - gci

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/Vladislav747/golang-project-order-system)
