FROM alpine:3.20

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY order-service ./order-service
COPY config/prod.yaml ./config/prod.yaml

EXPOSE 8080

ENV CONFIG_PATH=/app/config/prod.yaml

CMD ["./order-service", "--config", "/app/config/prod.yaml"]
