syntax = "proto3";

package order_event.v1;

option go_package = "github.com/Vladislav747/golang-project-order-system/internal/pkg/api/order_event/v1;order_event_v1";

service OrderEventService {
  rpc GetOrderEvents(GetOrderEventsRequest) returns (GetOrderEventsResponse);
}

enum EventSource {
  EVENT_SOURCE_UNSPECIFIED = 0;
  EVENT_SOURCE_HTTP_SYNC = 1; // http_sync
  EVENT_SOURCE_KAFKA = 2;     // kafka
}

message OrderEvent {
  string id = 1;
  string order_id = 2;
  string event_type = 3; // "created" | "updated" | "deleted"
  EventSource source = 4;     // "http_sync" | "kafka"
  bytes payload = 5;     // JSON
  string created_at = 6; // RFC3339
}

message GetOrderEventsRequest {}

message GetOrderEventsResponse {
  repeated OrderEvent events = 1;
}