syntax = "proto3";

package order_event.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/Vladislav747/golang-project-order-system/internal/pkg/api/order_event/v1;order_event_v1";

service OrderEventService {
  rpc GetOrderEvents(GetOrderEventsRequest) returns (GetOrderEventsResponse);
}

enum EventSource {
  UNSPECIFIED = 0;
  HTTP_SYNC = 1; // http_sync
  KAFKA = 2;     // kafka
}

enum EventType {
  CREATED = 0;
  UPDATED = 1;
  DELETED = 2;
}

message OrderEvent {
  string id = 1;
  string order_id = 2;
  EventType event_type = 3; // "created" | "updated" | "deleted"
  EventSource source = 4;     // "http_sync" | "kafka"
  bytes payload = 5;     // JSON
  google.protobuf.Timestamp created_at = 6;
}

message GetOrderEventsRequest {}

message GetOrderEventsResponse {
  repeated OrderEvent events = 1;
}