// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Vladislav747/golang-project-order-system/internal/model"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// MockRepositoryOrderEvent is an autogenerated mock type for the RepositoryOrderEvent type
type MockRepositoryOrderEvent struct {
	mock.Mock
}

type MockRepositoryOrderEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryOrderEvent) EXPECT() *MockRepositoryOrderEvent_Expecter {
	return &MockRepositoryOrderEvent_Expecter{mock: &_m.Mock}
}

// CreateOrderEvent provides a mock function with given fields: ctx, tx, order
func (_m *MockRepositoryOrderEvent) CreateOrderEvent(ctx context.Context, tx pgx.Tx, order model.OrderEvent) error {
	ret := _m.Called(ctx, tx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrderEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, model.OrderEvent) error); ok {
		r0 = rf(ctx, tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryOrderEvent_CreateOrderEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrderEvent'
type MockRepositoryOrderEvent_CreateOrderEvent_Call struct {
	*mock.Call
}

// CreateOrderEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - order model.OrderEvent
func (_e *MockRepositoryOrderEvent_Expecter) CreateOrderEvent(ctx interface{}, tx interface{}, order interface{}) *MockRepositoryOrderEvent_CreateOrderEvent_Call {
	return &MockRepositoryOrderEvent_CreateOrderEvent_Call{Call: _e.mock.On("CreateOrderEvent", ctx, tx, order)}
}

func (_c *MockRepositoryOrderEvent_CreateOrderEvent_Call) Run(run func(ctx context.Context, tx pgx.Tx, order model.OrderEvent)) *MockRepositoryOrderEvent_CreateOrderEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(model.OrderEvent))
	})
	return _c
}

func (_c *MockRepositoryOrderEvent_CreateOrderEvent_Call) Return(_a0 error) *MockRepositoryOrderEvent_CreateOrderEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryOrderEvent_CreateOrderEvent_Call) RunAndReturn(run func(context.Context, pgx.Tx, model.OrderEvent) error) *MockRepositoryOrderEvent_CreateOrderEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderEvents provides a mock function with given fields: ctx
func (_m *MockRepositoryOrderEvent) GetOrderEvents(ctx context.Context) ([]model.OrderEvent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderEvents")
	}

	var r0 []model.OrderEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.OrderEvent, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.OrderEvent); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OrderEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryOrderEvent_GetOrderEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderEvents'
type MockRepositoryOrderEvent_GetOrderEvents_Call struct {
	*mock.Call
}

// GetOrderEvents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryOrderEvent_Expecter) GetOrderEvents(ctx interface{}) *MockRepositoryOrderEvent_GetOrderEvents_Call {
	return &MockRepositoryOrderEvent_GetOrderEvents_Call{Call: _e.mock.On("GetOrderEvents", ctx)}
}

func (_c *MockRepositoryOrderEvent_GetOrderEvents_Call) Run(run func(ctx context.Context)) *MockRepositoryOrderEvent_GetOrderEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryOrderEvent_GetOrderEvents_Call) Return(_a0 []model.OrderEvent, _a1 error) *MockRepositoryOrderEvent_GetOrderEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryOrderEvent_GetOrderEvents_Call) RunAndReturn(run func(context.Context) ([]model.OrderEvent, error)) *MockRepositoryOrderEvent_GetOrderEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryOrderEvent creates a new instance of MockRepositoryOrderEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryOrderEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryOrderEvent {
	mock := &MockRepositoryOrderEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
