// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Vladislav747/golang-project-order-system/internal/model"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// MockRepositoryOutbox is an autogenerated mock type for the RepositoryOutbox type
type MockRepositoryOutbox struct {
	mock.Mock
}

type MockRepositoryOutbox_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryOutbox) EXPECT() *MockRepositoryOutbox_Expecter {
	return &MockRepositoryOutbox_Expecter{mock: &_m.Mock}
}

// CreateOutboxMessage provides a mock function with given fields: ctx, tx, message
func (_m *MockRepositoryOutbox) CreateOutboxMessage(ctx context.Context, tx pgx.Tx, message model.OutboxMessage) error {
	ret := _m.Called(ctx, tx, message)

	if len(ret) == 0 {
		panic("no return value specified for CreateOutboxMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, model.OutboxMessage) error); ok {
		r0 = rf(ctx, tx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryOutbox_CreateOutboxMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOutboxMessage'
type MockRepositoryOutbox_CreateOutboxMessage_Call struct {
	*mock.Call
}

// CreateOutboxMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - message model.OutboxMessage
func (_e *MockRepositoryOutbox_Expecter) CreateOutboxMessage(ctx interface{}, tx interface{}, message interface{}) *MockRepositoryOutbox_CreateOutboxMessage_Call {
	return &MockRepositoryOutbox_CreateOutboxMessage_Call{Call: _e.mock.On("CreateOutboxMessage", ctx, tx, message)}
}

func (_c *MockRepositoryOutbox_CreateOutboxMessage_Call) Run(run func(ctx context.Context, tx pgx.Tx, message model.OutboxMessage)) *MockRepositoryOutbox_CreateOutboxMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(model.OutboxMessage))
	})
	return _c
}

func (_c *MockRepositoryOutbox_CreateOutboxMessage_Call) Return(_a0 error) *MockRepositoryOutbox_CreateOutboxMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryOutbox_CreateOutboxMessage_Call) RunAndReturn(run func(context.Context, pgx.Tx, model.OutboxMessage) error) *MockRepositoryOutbox_CreateOutboxMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryOutbox creates a new instance of MockRepositoryOutbox. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryOutbox(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryOutbox {
	mock := &MockRepositoryOutbox{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
