// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Vladislav747/golang-project-order-system/internal/model"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: ctx, tx, order
func (_m *MockRepository) CreateOrder(ctx context.Context, tx pgx.Tx, order model.Order) error {
	ret := _m.Called(ctx, tx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, model.Order) error); ok {
		r0 = rf(ctx, tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - order model.Order
func (_e *MockRepository_Expecter) CreateOrder(ctx interface{}, tx interface{}, order interface{}) *MockRepository_CreateOrder_Call {
	return &MockRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, tx, order)}
}

func (_c *MockRepository_CreateOrder_Call) Run(run func(ctx context.Context, tx pgx.Tx, order model.Order)) *MockRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(model.Order))
	})
	return _c
}

func (_c *MockRepository_CreateOrder_Call) Return(_a0 error) *MockRepository_CreateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateOrder_Call) RunAndReturn(run func(context.Context, pgx.Tx, model.Order) error) *MockRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrder provides a mock function with given fields: ctx, tx, id
func (_m *MockRepository) DeleteOrder(ctx context.Context, tx pgx.Tx, id string) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrder'
type MockRepository_DeleteOrder_Call struct {
	*mock.Call
}

// DeleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id string
func (_e *MockRepository_Expecter) DeleteOrder(ctx interface{}, tx interface{}, id interface{}) *MockRepository_DeleteOrder_Call {
	return &MockRepository_DeleteOrder_Call{Call: _e.mock.On("DeleteOrder", ctx, tx, id)}
}

func (_c *MockRepository_DeleteOrder_Call) Run(run func(ctx context.Context, tx pgx.Tx, id string)) *MockRepository_DeleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteOrder_Call) Return(_a0 error) *MockRepository_DeleteOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteOrder_Call) RunAndReturn(run func(context.Context, pgx.Tx, string) error) *MockRepository_DeleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetOrder(ctx context.Context, id string) (model.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetOrder(ctx interface{}, id interface{}) *MockRepository_GetOrder_Call {
	return &MockRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *MockRepository_GetOrder_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetOrder_Call) Return(_a0 model.Order, _a1 error) *MockRepository_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetOrder_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *MockRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function with given fields: ctx
func (_m *MockRepository) GetOrders(ctx context.Context) ([]model.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockRepository_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetOrders(ctx interface{}) *MockRepository_GetOrders_Call {
	return &MockRepository_GetOrders_Call{Call: _e.mock.On("GetOrders", ctx)}
}

func (_c *MockRepository_GetOrders_Call) Run(run func(ctx context.Context)) *MockRepository_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetOrders_Call) Return(_a0 []model.Order, _a1 error) *MockRepository_GetOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetOrders_Call) RunAndReturn(run func(context.Context) ([]model.Order, error)) *MockRepository_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, tx, order
func (_m *MockRepository) UpdateOrder(ctx context.Context, tx pgx.Tx, order model.Order) error {
	ret := _m.Called(ctx, tx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, model.Order) error); ok {
		r0 = rf(ctx, tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type MockRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - order model.Order
func (_e *MockRepository_Expecter) UpdateOrder(ctx interface{}, tx interface{}, order interface{}) *MockRepository_UpdateOrder_Call {
	return &MockRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, tx, order)}
}

func (_c *MockRepository_UpdateOrder_Call) Run(run func(ctx context.Context, tx pgx.Tx, order model.Order)) *MockRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(model.Order))
	})
	return _c
}

func (_c *MockRepository_UpdateOrder_Call) Return(_a0 error) *MockRepository_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateOrder_Call) RunAndReturn(run func(context.Context, pgx.Tx, model.Order) error) *MockRepository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
