// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Vladislav747/golang-project-order-system/internal/model"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// MockRepositoryOrder is an autogenerated mock type for the RepositoryOrder type
type MockRepositoryOrder struct {
	mock.Mock
}

type MockRepositoryOrder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryOrder) EXPECT() *MockRepositoryOrder_Expecter {
	return &MockRepositoryOrder_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: ctx, tx, order
func (_m *MockRepositoryOrder) CreateOrder(ctx context.Context, tx pgx.Tx, order model.Order) error {
	ret := _m.Called(ctx, tx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, model.Order) error); ok {
		r0 = rf(ctx, tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryOrder_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockRepositoryOrder_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - order model.Order
func (_e *MockRepositoryOrder_Expecter) CreateOrder(ctx interface{}, tx interface{}, order interface{}) *MockRepositoryOrder_CreateOrder_Call {
	return &MockRepositoryOrder_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, tx, order)}
}

func (_c *MockRepositoryOrder_CreateOrder_Call) Run(run func(ctx context.Context, tx pgx.Tx, order model.Order)) *MockRepositoryOrder_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(model.Order))
	})
	return _c
}

func (_c *MockRepositoryOrder_CreateOrder_Call) Return(_a0 error) *MockRepositoryOrder_CreateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryOrder_CreateOrder_Call) RunAndReturn(run func(context.Context, pgx.Tx, model.Order) error) *MockRepositoryOrder_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrder provides a mock function with given fields: ctx, tx, id
func (_m *MockRepositoryOrder) DeleteOrder(ctx context.Context, tx pgx.Tx, id string) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryOrder_DeleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrder'
type MockRepositoryOrder_DeleteOrder_Call struct {
	*mock.Call
}

// DeleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id string
func (_e *MockRepositoryOrder_Expecter) DeleteOrder(ctx interface{}, tx interface{}, id interface{}) *MockRepositoryOrder_DeleteOrder_Call {
	return &MockRepositoryOrder_DeleteOrder_Call{Call: _e.mock.On("DeleteOrder", ctx, tx, id)}
}

func (_c *MockRepositoryOrder_DeleteOrder_Call) Run(run func(ctx context.Context, tx pgx.Tx, id string)) *MockRepositoryOrder_DeleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(string))
	})
	return _c
}

func (_c *MockRepositoryOrder_DeleteOrder_Call) Return(_a0 error) *MockRepositoryOrder_DeleteOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryOrder_DeleteOrder_Call) RunAndReturn(run func(context.Context, pgx.Tx, string) error) *MockRepositoryOrder_DeleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSoftOrder provides a mock function with given fields: ctx, tx, id
func (_m *MockRepositoryOrder) DeleteSoftOrder(ctx context.Context, tx pgx.Tx, id string) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSoftOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryOrder_DeleteSoftOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSoftOrder'
type MockRepositoryOrder_DeleteSoftOrder_Call struct {
	*mock.Call
}

// DeleteSoftOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id string
func (_e *MockRepositoryOrder_Expecter) DeleteSoftOrder(ctx interface{}, tx interface{}, id interface{}) *MockRepositoryOrder_DeleteSoftOrder_Call {
	return &MockRepositoryOrder_DeleteSoftOrder_Call{Call: _e.mock.On("DeleteSoftOrder", ctx, tx, id)}
}

func (_c *MockRepositoryOrder_DeleteSoftOrder_Call) Run(run func(ctx context.Context, tx pgx.Tx, id string)) *MockRepositoryOrder_DeleteSoftOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(string))
	})
	return _c
}

func (_c *MockRepositoryOrder_DeleteSoftOrder_Call) Return(_a0 error) *MockRepositoryOrder_DeleteSoftOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryOrder_DeleteSoftOrder_Call) RunAndReturn(run func(context.Context, pgx.Tx, string) error) *MockRepositoryOrder_DeleteSoftOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *MockRepositoryOrder) GetOrder(ctx context.Context, id string) (model.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryOrder_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockRepositoryOrder_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepositoryOrder_Expecter) GetOrder(ctx interface{}, id interface{}) *MockRepositoryOrder_GetOrder_Call {
	return &MockRepositoryOrder_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *MockRepositoryOrder_GetOrder_Call) Run(run func(ctx context.Context, id string)) *MockRepositoryOrder_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepositoryOrder_GetOrder_Call) Return(_a0 model.Order, _a1 error) *MockRepositoryOrder_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryOrder_GetOrder_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *MockRepositoryOrder_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function with given fields: ctx
func (_m *MockRepositoryOrder) GetOrders(ctx context.Context) ([]model.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryOrder_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockRepositoryOrder_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryOrder_Expecter) GetOrders(ctx interface{}) *MockRepositoryOrder_GetOrders_Call {
	return &MockRepositoryOrder_GetOrders_Call{Call: _e.mock.On("GetOrders", ctx)}
}

func (_c *MockRepositoryOrder_GetOrders_Call) Run(run func(ctx context.Context)) *MockRepositoryOrder_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryOrder_GetOrders_Call) Return(_a0 []model.Order, _a1 error) *MockRepositoryOrder_GetOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryOrder_GetOrders_Call) RunAndReturn(run func(context.Context) ([]model.Order, error)) *MockRepositoryOrder_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, tx, order
func (_m *MockRepositoryOrder) UpdateOrder(ctx context.Context, tx pgx.Tx, order model.Order) error {
	ret := _m.Called(ctx, tx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, model.Order) error); ok {
		r0 = rf(ctx, tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryOrder_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type MockRepositoryOrder_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - order model.Order
func (_e *MockRepositoryOrder_Expecter) UpdateOrder(ctx interface{}, tx interface{}, order interface{}) *MockRepositoryOrder_UpdateOrder_Call {
	return &MockRepositoryOrder_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, tx, order)}
}

func (_c *MockRepositoryOrder_UpdateOrder_Call) Run(run func(ctx context.Context, tx pgx.Tx, order model.Order)) *MockRepositoryOrder_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(model.Order))
	})
	return _c
}

func (_c *MockRepositoryOrder_UpdateOrder_Call) Return(_a0 error) *MockRepositoryOrder_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryOrder_UpdateOrder_Call) RunAndReturn(run func(context.Context, pgx.Tx, model.Order) error) *MockRepositoryOrder_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryOrder creates a new instance of MockRepositoryOrder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryOrder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryOrder {
	mock := &MockRepositoryOrder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
