// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Vladislav747/golang-project-order-system/internal/model"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	uuid "github.com/google/uuid"
)

// MockRepositoryOutbox is an autogenerated mock type for the RepositoryOutbox type
type MockRepositoryOutbox struct {
	mock.Mock
}

type MockRepositoryOutbox_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryOutbox) EXPECT() *MockRepositoryOutbox_Expecter {
	return &MockRepositoryOutbox_Expecter{mock: &_m.Mock}
}

// CreateOutboxMessage provides a mock function with given fields: ctx, tx, message
func (_m *MockRepositoryOutbox) CreateOutboxMessage(ctx context.Context, tx pgx.Tx, message model.OutboxMessage) error {
	ret := _m.Called(ctx, tx, message)

	if len(ret) == 0 {
		panic("no return value specified for CreateOutboxMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, model.OutboxMessage) error); ok {
		r0 = rf(ctx, tx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryOutbox_CreateOutboxMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOutboxMessage'
type MockRepositoryOutbox_CreateOutboxMessage_Call struct {
	*mock.Call
}

// CreateOutboxMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - message model.OutboxMessage
func (_e *MockRepositoryOutbox_Expecter) CreateOutboxMessage(ctx interface{}, tx interface{}, message interface{}) *MockRepositoryOutbox_CreateOutboxMessage_Call {
	return &MockRepositoryOutbox_CreateOutboxMessage_Call{Call: _e.mock.On("CreateOutboxMessage", ctx, tx, message)}
}

func (_c *MockRepositoryOutbox_CreateOutboxMessage_Call) Run(run func(ctx context.Context, tx pgx.Tx, message model.OutboxMessage)) *MockRepositoryOutbox_CreateOutboxMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(model.OutboxMessage))
	})
	return _c
}

func (_c *MockRepositoryOutbox_CreateOutboxMessage_Call) Return(_a0 error) *MockRepositoryOutbox_CreateOutboxMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryOutbox_CreateOutboxMessage_Call) RunAndReturn(run func(context.Context, pgx.Tx, model.OutboxMessage) error) *MockRepositoryOutbox_CreateOutboxMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetOutboxMessagesUnpublished provides a mock function with given fields: ctx, limit, maxAttempts
func (_m *MockRepositoryOutbox) GetOutboxMessagesUnpublished(ctx context.Context, limit int, maxAttempts int) ([]model.OutboxMessage, error) {
	ret := _m.Called(ctx, limit, maxAttempts)

	if len(ret) == 0 {
		panic("no return value specified for GetOutboxMessagesUnpublished")
	}

	var r0 []model.OutboxMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]model.OutboxMessage, error)); ok {
		return rf(ctx, limit, maxAttempts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []model.OutboxMessage); ok {
		r0 = rf(ctx, limit, maxAttempts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OutboxMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, maxAttempts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryOutbox_GetOutboxMessagesUnpublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOutboxMessagesUnpublished'
type MockRepositoryOutbox_GetOutboxMessagesUnpublished_Call struct {
	*mock.Call
}

// GetOutboxMessagesUnpublished is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - maxAttempts int
func (_e *MockRepositoryOutbox_Expecter) GetOutboxMessagesUnpublished(ctx interface{}, limit interface{}, maxAttempts interface{}) *MockRepositoryOutbox_GetOutboxMessagesUnpublished_Call {
	return &MockRepositoryOutbox_GetOutboxMessagesUnpublished_Call{Call: _e.mock.On("GetOutboxMessagesUnpublished", ctx, limit, maxAttempts)}
}

func (_c *MockRepositoryOutbox_GetOutboxMessagesUnpublished_Call) Run(run func(ctx context.Context, limit int, maxAttempts int)) *MockRepositoryOutbox_GetOutboxMessagesUnpublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRepositoryOutbox_GetOutboxMessagesUnpublished_Call) Return(_a0 []model.OutboxMessage, _a1 error) *MockRepositoryOutbox_GetOutboxMessagesUnpublished_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryOutbox_GetOutboxMessagesUnpublished_Call) RunAndReturn(run func(context.Context, int, int) ([]model.OutboxMessage, error)) *MockRepositoryOutbox_GetOutboxMessagesUnpublished_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOutboxMessageFailed provides a mock function with given fields: ctx, tx, id, lastError
func (_m *MockRepositoryOutbox) MarkOutboxMessageFailed(ctx context.Context, tx pgx.Tx, id uuid.UUID, lastError string) error {
	ret := _m.Called(ctx, tx, id, lastError)

	if len(ret) == 0 {
		panic("no return value specified for MarkOutboxMessageFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID, string) error); ok {
		r0 = rf(ctx, tx, id, lastError)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryOutbox_MarkOutboxMessageFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOutboxMessageFailed'
type MockRepositoryOutbox_MarkOutboxMessageFailed_Call struct {
	*mock.Call
}

// MarkOutboxMessageFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id uuid.UUID
//   - lastError string
func (_e *MockRepositoryOutbox_Expecter) MarkOutboxMessageFailed(ctx interface{}, tx interface{}, id interface{}, lastError interface{}) *MockRepositoryOutbox_MarkOutboxMessageFailed_Call {
	return &MockRepositoryOutbox_MarkOutboxMessageFailed_Call{Call: _e.mock.On("MarkOutboxMessageFailed", ctx, tx, id, lastError)}
}

func (_c *MockRepositoryOutbox_MarkOutboxMessageFailed_Call) Run(run func(ctx context.Context, tx pgx.Tx, id uuid.UUID, lastError string)) *MockRepositoryOutbox_MarkOutboxMessageFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockRepositoryOutbox_MarkOutboxMessageFailed_Call) Return(_a0 error) *MockRepositoryOutbox_MarkOutboxMessageFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryOutbox_MarkOutboxMessageFailed_Call) RunAndReturn(run func(context.Context, pgx.Tx, uuid.UUID, string) error) *MockRepositoryOutbox_MarkOutboxMessageFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOutboxMessagePublished provides a mock function with given fields: ctx, tx, id
func (_m *MockRepositoryOutbox) MarkOutboxMessagePublished(ctx context.Context, tx pgx.Tx, id uuid.UUID) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkOutboxMessagePublished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryOutbox_MarkOutboxMessagePublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOutboxMessagePublished'
type MockRepositoryOutbox_MarkOutboxMessagePublished_Call struct {
	*mock.Call
}

// MarkOutboxMessagePublished is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id uuid.UUID
func (_e *MockRepositoryOutbox_Expecter) MarkOutboxMessagePublished(ctx interface{}, tx interface{}, id interface{}) *MockRepositoryOutbox_MarkOutboxMessagePublished_Call {
	return &MockRepositoryOutbox_MarkOutboxMessagePublished_Call{Call: _e.mock.On("MarkOutboxMessagePublished", ctx, tx, id)}
}

func (_c *MockRepositoryOutbox_MarkOutboxMessagePublished_Call) Run(run func(ctx context.Context, tx pgx.Tx, id uuid.UUID)) *MockRepositoryOutbox_MarkOutboxMessagePublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepositoryOutbox_MarkOutboxMessagePublished_Call) Return(_a0 error) *MockRepositoryOutbox_MarkOutboxMessagePublished_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryOutbox_MarkOutboxMessagePublished_Call) RunAndReturn(run func(context.Context, pgx.Tx, uuid.UUID) error) *MockRepositoryOutbox_MarkOutboxMessagePublished_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryOutbox creates a new instance of MockRepositoryOutbox. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryOutbox(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryOutbox {
	mock := &MockRepositoryOutbox{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
