// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: order_event/v1/order_event.proto

package order_event_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventSource int32

const (
	EventSource_UNSPECIFIED EventSource = 0
	EventSource_HTTP_SYNC   EventSource = 1 // http_sync
	EventSource_KAFKA       EventSource = 2 // kafka
)

// Enum value maps for EventSource.
var (
	EventSource_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "HTTP_SYNC",
		2: "KAFKA",
	}
	EventSource_value = map[string]int32{
		"UNSPECIFIED": 0,
		"HTTP_SYNC":   1,
		"KAFKA":       2,
	}
)

func (x EventSource) Enum() *EventSource {
	p := new(EventSource)
	*p = x
	return p
}

func (x EventSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventSource) Descriptor() protoreflect.EnumDescriptor {
	return file_order_event_v1_order_event_proto_enumTypes[0].Descriptor()
}

func (EventSource) Type() protoreflect.EnumType {
	return &file_order_event_v1_order_event_proto_enumTypes[0]
}

func (x EventSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventSource.Descriptor instead.
func (EventSource) EnumDescriptor() ([]byte, []int) {
	return file_order_event_v1_order_event_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_CREATED EventType = 0
	EventType_UPDATED EventType = 1
	EventType_DELETED EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "CREATED",
		1: "UPDATED",
		2: "DELETED",
	}
	EventType_value = map[string]int32{
		"CREATED": 0,
		"UPDATED": 1,
		"DELETED": 2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_event_v1_order_event_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_order_event_v1_order_event_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_order_event_v1_order_event_proto_rawDescGZIP(), []int{1}
}

type OrderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	EventType     EventType              `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=order_event.v1.EventType" json:"event_type,omitempty"` // "created" | "updated" | "deleted"
	Source        EventSource            `protobuf:"varint,4,opt,name=source,proto3,enum=order_event.v1.EventSource" json:"source,omitempty"`                      // "http_sync" | "kafka"
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                                                     // JSON
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	mi := &file_order_event_v1_order_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_order_event_v1_order_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_order_event_v1_order_event_proto_rawDescGZIP(), []int{0}
}

func (x *OrderEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_CREATED
}

func (x *OrderEvent) GetSource() EventSource {
	if x != nil {
		return x.Source
	}
	return EventSource_UNSPECIFIED
}

func (x *OrderEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OrderEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetOrderEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderEventsRequest) Reset() {
	*x = GetOrderEventsRequest{}
	mi := &file_order_event_v1_order_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderEventsRequest) ProtoMessage() {}

func (x *GetOrderEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_event_v1_order_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderEventsRequest.ProtoReflect.Descriptor instead.
func (*GetOrderEventsRequest) Descriptor() ([]byte, []int) {
	return file_order_event_v1_order_event_proto_rawDescGZIP(), []int{1}
}

type GetOrderEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*OrderEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderEventsResponse) Reset() {
	*x = GetOrderEventsResponse{}
	mi := &file_order_event_v1_order_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderEventsResponse) ProtoMessage() {}

func (x *GetOrderEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_event_v1_order_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderEventsResponse.ProtoReflect.Descriptor instead.
func (*GetOrderEventsResponse) Descriptor() ([]byte, []int) {
	return file_order_event_v1_order_event_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderEventsResponse) GetEvents() []*OrderEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_order_event_v1_order_event_proto protoreflect.FileDescriptor

const file_order_event_v1_order_event_proto_rawDesc = "" +
	"\n" +
	" order_event/v1/order_event.proto\x12\x0eorder_event.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x01\n" +
	"\n" +
	"OrderEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x128\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\x19.order_event.v1.EventTypeR\teventType\x123\n" +
	"\x06source\x18\x04 \x01(\x0e2\x1b.order_event.v1.EventSourceR\x06source\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x17\n" +
	"\x15GetOrderEventsRequest\"L\n" +
	"\x16GetOrderEventsResponse\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.order_event.v1.OrderEventR\x06events*8\n" +
	"\vEventSource\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\r\n" +
	"\tHTTP_SYNC\x10\x01\x12\t\n" +
	"\x05KAFKA\x10\x02*2\n" +
	"\tEventType\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aUPDATED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x022t\n" +
	"\x11OrderEventService\x12_\n" +
	"\x0eGetOrderEvents\x12%.order_event.v1.GetOrderEventsRequest\x1a&.order_event.v1.GetOrderEventsResponseBdZbgithub.com/Vladislav747/golang-project-order-system/internal/pkg/api/order_event/v1;order_event_v1b\x06proto3"

var (
	file_order_event_v1_order_event_proto_rawDescOnce sync.Once
	file_order_event_v1_order_event_proto_rawDescData []byte
)

func file_order_event_v1_order_event_proto_rawDescGZIP() []byte {
	file_order_event_v1_order_event_proto_rawDescOnce.Do(func() {
		file_order_event_v1_order_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_event_v1_order_event_proto_rawDesc), len(file_order_event_v1_order_event_proto_rawDesc)))
	})
	return file_order_event_v1_order_event_proto_rawDescData
}

var file_order_event_v1_order_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_order_event_v1_order_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_order_event_v1_order_event_proto_goTypes = []any{
	(EventSource)(0),               // 0: order_event.v1.EventSource
	(EventType)(0),                 // 1: order_event.v1.EventType
	(*OrderEvent)(nil),             // 2: order_event.v1.OrderEvent
	(*GetOrderEventsRequest)(nil),  // 3: order_event.v1.GetOrderEventsRequest
	(*GetOrderEventsResponse)(nil), // 4: order_event.v1.GetOrderEventsResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_order_event_v1_order_event_proto_depIdxs = []int32{
	1, // 0: order_event.v1.OrderEvent.event_type:type_name -> order_event.v1.EventType
	0, // 1: order_event.v1.OrderEvent.source:type_name -> order_event.v1.EventSource
	5, // 2: order_event.v1.OrderEvent.created_at:type_name -> google.protobuf.Timestamp
	2, // 3: order_event.v1.GetOrderEventsResponse.events:type_name -> order_event.v1.OrderEvent
	3, // 4: order_event.v1.OrderEventService.GetOrderEvents:input_type -> order_event.v1.GetOrderEventsRequest
	4, // 5: order_event.v1.OrderEventService.GetOrderEvents:output_type -> order_event.v1.GetOrderEventsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_order_event_v1_order_event_proto_init() }
func file_order_event_v1_order_event_proto_init() {
	if File_order_event_v1_order_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_event_v1_order_event_proto_rawDesc), len(file_order_event_v1_order_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_event_v1_order_event_proto_goTypes,
		DependencyIndexes: file_order_event_v1_order_event_proto_depIdxs,
		EnumInfos:         file_order_event_v1_order_event_proto_enumTypes,
		MessageInfos:      file_order_event_v1_order_event_proto_msgTypes,
	}.Build()
	File_order_event_v1_order_event_proto = out.File
	file_order_event_v1_order_event_proto_goTypes = nil
	file_order_event_v1_order_event_proto_depIdxs = nil
}
