// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: order_event/v1/order_event.proto

package order_event_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderEventService_GetOrderEvents_FullMethodName = "/order_event.v1.OrderEventService/GetOrderEvents"
)

// OrderEventServiceClient is the client API for OrderEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderEventServiceClient interface {
	GetOrderEvents(ctx context.Context, in *GetOrderEventsRequest, opts ...grpc.CallOption) (*GetOrderEventsResponse, error)
}

type orderEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderEventServiceClient(cc grpc.ClientConnInterface) OrderEventServiceClient {
	return &orderEventServiceClient{cc}
}

func (c *orderEventServiceClient) GetOrderEvents(ctx context.Context, in *GetOrderEventsRequest, opts ...grpc.CallOption) (*GetOrderEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderEventsResponse)
	err := c.cc.Invoke(ctx, OrderEventService_GetOrderEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderEventServiceServer is the server API for OrderEventService service.
// All implementations must embed UnimplementedOrderEventServiceServer
// for forward compatibility.
type OrderEventServiceServer interface {
	GetOrderEvents(context.Context, *GetOrderEventsRequest) (*GetOrderEventsResponse, error)
	mustEmbedUnimplementedOrderEventServiceServer()
}

// UnimplementedOrderEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderEventServiceServer struct{}

func (UnimplementedOrderEventServiceServer) GetOrderEvents(context.Context, *GetOrderEventsRequest) (*GetOrderEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderEvents not implemented")
}
func (UnimplementedOrderEventServiceServer) mustEmbedUnimplementedOrderEventServiceServer() {}
func (UnimplementedOrderEventServiceServer) testEmbeddedByValue()                           {}

// UnsafeOrderEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderEventServiceServer will
// result in compilation errors.
type UnsafeOrderEventServiceServer interface {
	mustEmbedUnimplementedOrderEventServiceServer()
}

func RegisterOrderEventServiceServer(s grpc.ServiceRegistrar, srv OrderEventServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderEventService_ServiceDesc, srv)
}

func _OrderEventService_GetOrderEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderEventServiceServer).GetOrderEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderEventService_GetOrderEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderEventServiceServer).GetOrderEvents(ctx, req.(*GetOrderEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderEventService_ServiceDesc is the grpc.ServiceDesc for OrderEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order_event.v1.OrderEventService",
	HandlerType: (*OrderEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderEvents",
			Handler:    _OrderEventService_GetOrderEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_event/v1/order_event.proto",
}
