// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	orderv1 "github.com/Vladislav747/golang-project-order-system/internal/pkg/api/order/v1"
)

// MockOrderServiceClient is an autogenerated mock type for the OrderServiceClient type
type MockOrderServiceClient struct {
	mock.Mock
}

type MockOrderServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderServiceClient) EXPECT() *MockOrderServiceClient_Expecter {
	return &MockOrderServiceClient_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: ctx, in, opts
func (_m *MockOrderServiceClient) CreateOrder(ctx context.Context, in *orderv1.CreateOrderRequest, opts ...grpc.CallOption) (*orderv1.CreateOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *orderv1.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orderv1.CreateOrderRequest, ...grpc.CallOption) (*orderv1.CreateOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orderv1.CreateOrderRequest, ...grpc.CallOption) *orderv1.CreateOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orderv1.CreateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orderv1.CreateOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderServiceClient_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderServiceClient_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *orderv1.CreateOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockOrderServiceClient_Expecter) CreateOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockOrderServiceClient_CreateOrder_Call {
	return &MockOrderServiceClient_CreateOrder_Call{Call: _e.mock.On("CreateOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockOrderServiceClient_CreateOrder_Call) Run(run func(ctx context.Context, in *orderv1.CreateOrderRequest, opts ...grpc.CallOption)) *MockOrderServiceClient_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*orderv1.CreateOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockOrderServiceClient_CreateOrder_Call) Return(_a0 *orderv1.CreateOrderResponse, _a1 error) *MockOrderServiceClient_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderServiceClient_CreateOrder_Call) RunAndReturn(run func(context.Context, *orderv1.CreateOrderRequest, ...grpc.CallOption) (*orderv1.CreateOrderResponse, error)) *MockOrderServiceClient_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrder provides a mock function with given fields: ctx, in, opts
func (_m *MockOrderServiceClient) DeleteOrder(ctx context.Context, in *orderv1.DeleteOrderRequest, opts ...grpc.CallOption) (*orderv1.DeleteOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 *orderv1.DeleteOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orderv1.DeleteOrderRequest, ...grpc.CallOption) (*orderv1.DeleteOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orderv1.DeleteOrderRequest, ...grpc.CallOption) *orderv1.DeleteOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orderv1.DeleteOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orderv1.DeleteOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderServiceClient_DeleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrder'
type MockOrderServiceClient_DeleteOrder_Call struct {
	*mock.Call
}

// DeleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *orderv1.DeleteOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockOrderServiceClient_Expecter) DeleteOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockOrderServiceClient_DeleteOrder_Call {
	return &MockOrderServiceClient_DeleteOrder_Call{Call: _e.mock.On("DeleteOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockOrderServiceClient_DeleteOrder_Call) Run(run func(ctx context.Context, in *orderv1.DeleteOrderRequest, opts ...grpc.CallOption)) *MockOrderServiceClient_DeleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*orderv1.DeleteOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockOrderServiceClient_DeleteOrder_Call) Return(_a0 *orderv1.DeleteOrderResponse, _a1 error) *MockOrderServiceClient_DeleteOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderServiceClient_DeleteOrder_Call) RunAndReturn(run func(context.Context, *orderv1.DeleteOrderRequest, ...grpc.CallOption) (*orderv1.DeleteOrderResponse, error)) *MockOrderServiceClient_DeleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, in, opts
func (_m *MockOrderServiceClient) GetOrder(ctx context.Context, in *orderv1.GetOrderRequest, opts ...grpc.CallOption) (*orderv1.GetOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *orderv1.GetOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orderv1.GetOrderRequest, ...grpc.CallOption) (*orderv1.GetOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orderv1.GetOrderRequest, ...grpc.CallOption) *orderv1.GetOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orderv1.GetOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orderv1.GetOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderServiceClient_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderServiceClient_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *orderv1.GetOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockOrderServiceClient_Expecter) GetOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockOrderServiceClient_GetOrder_Call {
	return &MockOrderServiceClient_GetOrder_Call{Call: _e.mock.On("GetOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockOrderServiceClient_GetOrder_Call) Run(run func(ctx context.Context, in *orderv1.GetOrderRequest, opts ...grpc.CallOption)) *MockOrderServiceClient_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*orderv1.GetOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockOrderServiceClient_GetOrder_Call) Return(_a0 *orderv1.GetOrderResponse, _a1 error) *MockOrderServiceClient_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderServiceClient_GetOrder_Call) RunAndReturn(run func(context.Context, *orderv1.GetOrderRequest, ...grpc.CallOption) (*orderv1.GetOrderResponse, error)) *MockOrderServiceClient_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function with given fields: ctx, in, opts
func (_m *MockOrderServiceClient) GetOrders(ctx context.Context, in *orderv1.GetOrdersRequest, opts ...grpc.CallOption) (*orderv1.GetOrdersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 *orderv1.GetOrdersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orderv1.GetOrdersRequest, ...grpc.CallOption) (*orderv1.GetOrdersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orderv1.GetOrdersRequest, ...grpc.CallOption) *orderv1.GetOrdersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orderv1.GetOrdersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orderv1.GetOrdersRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderServiceClient_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockOrderServiceClient_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - in *orderv1.GetOrdersRequest
//   - opts ...grpc.CallOption
func (_e *MockOrderServiceClient_Expecter) GetOrders(ctx interface{}, in interface{}, opts ...interface{}) *MockOrderServiceClient_GetOrders_Call {
	return &MockOrderServiceClient_GetOrders_Call{Call: _e.mock.On("GetOrders",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockOrderServiceClient_GetOrders_Call) Run(run func(ctx context.Context, in *orderv1.GetOrdersRequest, opts ...grpc.CallOption)) *MockOrderServiceClient_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*orderv1.GetOrdersRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockOrderServiceClient_GetOrders_Call) Return(_a0 *orderv1.GetOrdersResponse, _a1 error) *MockOrderServiceClient_GetOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderServiceClient_GetOrders_Call) RunAndReturn(run func(context.Context, *orderv1.GetOrdersRequest, ...grpc.CallOption) (*orderv1.GetOrdersResponse, error)) *MockOrderServiceClient_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, in, opts
func (_m *MockOrderServiceClient) UpdateOrder(ctx context.Context, in *orderv1.UpdateOrderRequest, opts ...grpc.CallOption) (*orderv1.UpdateOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 *orderv1.UpdateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *orderv1.UpdateOrderRequest, ...grpc.CallOption) (*orderv1.UpdateOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *orderv1.UpdateOrderRequest, ...grpc.CallOption) *orderv1.UpdateOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orderv1.UpdateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *orderv1.UpdateOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderServiceClient_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type MockOrderServiceClient_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *orderv1.UpdateOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockOrderServiceClient_Expecter) UpdateOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockOrderServiceClient_UpdateOrder_Call {
	return &MockOrderServiceClient_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockOrderServiceClient_UpdateOrder_Call) Run(run func(ctx context.Context, in *orderv1.UpdateOrderRequest, opts ...grpc.CallOption)) *MockOrderServiceClient_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*orderv1.UpdateOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockOrderServiceClient_UpdateOrder_Call) Return(_a0 *orderv1.UpdateOrderResponse, _a1 error) *MockOrderServiceClient_UpdateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderServiceClient_UpdateOrder_Call) RunAndReturn(run func(context.Context, *orderv1.UpdateOrderRequest, ...grpc.CallOption) (*orderv1.UpdateOrderResponse, error)) *MockOrderServiceClient_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderServiceClient creates a new instance of MockOrderServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderServiceClient {
	mock := &MockOrderServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
