// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Vladislav747/golang-project-order-system/internal/model"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	uuid "github.com/google/uuid"
)

// MockOutboxRepository is an autogenerated mock type for the OutboxRepository type
type MockOutboxRepository struct {
	mock.Mock
}

type MockOutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRepository) EXPECT() *MockOutboxRepository_Expecter {
	return &MockOutboxRepository_Expecter{mock: &_m.Mock}
}

// GetOutboxMessagesUnpublished provides a mock function with given fields: ctx, limit
func (_m *MockOutboxRepository) GetOutboxMessagesUnpublished(ctx context.Context, limit int) ([]model.OutboxMessage, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetOutboxMessagesUnpublished")
	}

	var r0 []model.OutboxMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.OutboxMessage, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.OutboxMessage); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OutboxMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOutboxRepository_GetOutboxMessagesUnpublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOutboxMessagesUnpublished'
type MockOutboxRepository_GetOutboxMessagesUnpublished_Call struct {
	*mock.Call
}

// GetOutboxMessagesUnpublished is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockOutboxRepository_Expecter) GetOutboxMessagesUnpublished(ctx interface{}, limit interface{}) *MockOutboxRepository_GetOutboxMessagesUnpublished_Call {
	return &MockOutboxRepository_GetOutboxMessagesUnpublished_Call{Call: _e.mock.On("GetOutboxMessagesUnpublished", ctx, limit)}
}

func (_c *MockOutboxRepository_GetOutboxMessagesUnpublished_Call) Run(run func(ctx context.Context, limit int)) *MockOutboxRepository_GetOutboxMessagesUnpublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockOutboxRepository_GetOutboxMessagesUnpublished_Call) Return(_a0 []model.OutboxMessage, _a1 error) *MockOutboxRepository_GetOutboxMessagesUnpublished_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOutboxRepository_GetOutboxMessagesUnpublished_Call) RunAndReturn(run func(context.Context, int) ([]model.OutboxMessage, error)) *MockOutboxRepository_GetOutboxMessagesUnpublished_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOutboxMessageFailed provides a mock function with given fields: ctx, tx, id, lastError
func (_m *MockOutboxRepository) MarkOutboxMessageFailed(ctx context.Context, tx pgx.Tx, id uuid.UUID, lastError string) error {
	ret := _m.Called(ctx, tx, id, lastError)

	if len(ret) == 0 {
		panic("no return value specified for MarkOutboxMessageFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID, string) error); ok {
		r0 = rf(ctx, tx, id, lastError)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepository_MarkOutboxMessageFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOutboxMessageFailed'
type MockOutboxRepository_MarkOutboxMessageFailed_Call struct {
	*mock.Call
}

// MarkOutboxMessageFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id uuid.UUID
//   - lastError string
func (_e *MockOutboxRepository_Expecter) MarkOutboxMessageFailed(ctx interface{}, tx interface{}, id interface{}, lastError interface{}) *MockOutboxRepository_MarkOutboxMessageFailed_Call {
	return &MockOutboxRepository_MarkOutboxMessageFailed_Call{Call: _e.mock.On("MarkOutboxMessageFailed", ctx, tx, id, lastError)}
}

func (_c *MockOutboxRepository_MarkOutboxMessageFailed_Call) Run(run func(ctx context.Context, tx pgx.Tx, id uuid.UUID, lastError string)) *MockOutboxRepository_MarkOutboxMessageFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockOutboxRepository_MarkOutboxMessageFailed_Call) Return(_a0 error) *MockOutboxRepository_MarkOutboxMessageFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepository_MarkOutboxMessageFailed_Call) RunAndReturn(run func(context.Context, pgx.Tx, uuid.UUID, string) error) *MockOutboxRepository_MarkOutboxMessageFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOutboxMessagePublished provides a mock function with given fields: ctx, tx, id
func (_m *MockOutboxRepository) MarkOutboxMessagePublished(ctx context.Context, tx pgx.Tx, id uuid.UUID) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkOutboxMessagePublished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepository_MarkOutboxMessagePublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOutboxMessagePublished'
type MockOutboxRepository_MarkOutboxMessagePublished_Call struct {
	*mock.Call
}

// MarkOutboxMessagePublished is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id uuid.UUID
func (_e *MockOutboxRepository_Expecter) MarkOutboxMessagePublished(ctx interface{}, tx interface{}, id interface{}) *MockOutboxRepository_MarkOutboxMessagePublished_Call {
	return &MockOutboxRepository_MarkOutboxMessagePublished_Call{Call: _e.mock.On("MarkOutboxMessagePublished", ctx, tx, id)}
}

func (_c *MockOutboxRepository_MarkOutboxMessagePublished_Call) Run(run func(ctx context.Context, tx pgx.Tx, id uuid.UUID)) *MockOutboxRepository_MarkOutboxMessagePublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockOutboxRepository_MarkOutboxMessagePublished_Call) Return(_a0 error) *MockOutboxRepository_MarkOutboxMessagePublished_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepository_MarkOutboxMessagePublished_Call) RunAndReturn(run func(context.Context, pgx.Tx, uuid.UUID) error) *MockOutboxRepository_MarkOutboxMessagePublished_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboxRepository creates a new instance of MockOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRepository {
	mock := &MockOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
