// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockOutboxCleanerRepository is an autogenerated mock type for the OutboxCleanerRepository type
type MockOutboxCleanerRepository struct {
	mock.Mock
}

type MockOutboxCleanerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxCleanerRepository) EXPECT() *MockOutboxCleanerRepository_Expecter {
	return &MockOutboxCleanerRepository_Expecter{mock: &_m.Mock}
}

// CleanOutboxMessages provides a mock function with given fields: ctx, tx, retention, maxAttempts
func (_m *MockOutboxCleanerRepository) CleanOutboxMessages(ctx context.Context, tx pgx.Tx, retention time.Duration, maxAttempts int) error {
	ret := _m.Called(ctx, tx, retention, maxAttempts)

	if len(ret) == 0 {
		panic("no return value specified for CleanOutboxMessages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, time.Duration, int) error); ok {
		r0 = rf(ctx, tx, retention, maxAttempts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxCleanerRepository_CleanOutboxMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanOutboxMessages'
type MockOutboxCleanerRepository_CleanOutboxMessages_Call struct {
	*mock.Call
}

// CleanOutboxMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - retention time.Duration
//   - maxAttempts int
func (_e *MockOutboxCleanerRepository_Expecter) CleanOutboxMessages(ctx interface{}, tx interface{}, retention interface{}, maxAttempts interface{}) *MockOutboxCleanerRepository_CleanOutboxMessages_Call {
	return &MockOutboxCleanerRepository_CleanOutboxMessages_Call{Call: _e.mock.On("CleanOutboxMessages", ctx, tx, retention, maxAttempts)}
}

func (_c *MockOutboxCleanerRepository_CleanOutboxMessages_Call) Run(run func(ctx context.Context, tx pgx.Tx, retention time.Duration, maxAttempts int)) *MockOutboxCleanerRepository_CleanOutboxMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(time.Duration), args[3].(int))
	})
	return _c
}

func (_c *MockOutboxCleanerRepository_CleanOutboxMessages_Call) Return(_a0 error) *MockOutboxCleanerRepository_CleanOutboxMessages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxCleanerRepository_CleanOutboxMessages_Call) RunAndReturn(run func(context.Context, pgx.Tx, time.Duration, int) error) *MockOutboxCleanerRepository_CleanOutboxMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboxCleanerRepository creates a new instance of MockOutboxCleanerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxCleanerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxCleanerRepository {
	mock := &MockOutboxCleanerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
